GET http://localhost:8080/

###
POST http://localhost:8080/abrigos
Content-Type: application/json

{
    "nome": "Abrigo Teste 2",
    "telefone": "4312341235",
    "email": "email2@email.com"
}

###
GET http://localhost:8080/abrigos

###
POST http://localhost:8080/pets
Content-Type: application/json

{
    "tipo": "CACHORRO",
    "nome": "Cachorro 01",
    "raca": "Raça 01",
    "idade": 3,
    "cor": "Cor 01",
    "peso": 12.32
}